#!/usr/bin/env bash

set -euo pipefail

repo_root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
output_file="$repo_root/docs/print/repository-readthrough.md"

cd "$repo_root"
mkdir -p "$(dirname "$output_file")"

{
  printf '# Repository documentation read-through\n\n'
  printf '> Generated by `scripts/bundle-docs.sh`. This file is local reading material and is not source documentation.\n\n'

  while IFS= read -r file; do
    printf '\n---\n\n'
    printf '# Source: %s\n\n' "$file"
    cat "$file"
    printf '\n'
  done < <(
    {
      printf '%s\n' README.md
      find apps infra specs .specify/memory -type f -name '*.md' -print
      find docs -path docs/print -prune -o -type f -name '*.md' -print
    } | sort -u
  )
} > "$output_file"

echo "Wrote $output_file"